// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Torque.Data;

#nullable disable

namespace torque_backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904183012_UserModerationFields")]
    partial class UserModerationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Torque.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiUse")
                        .HasColumnType("text")
                        .HasColumnName("ai_use");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid>("ClaimedByReviewer")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_reviewer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("text")
                        .HasColumnName("demo_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("HackatimeProjectNames")
                        .HasColumnType("text[]")
                        .HasColumnName("hackatime_project_names");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ReadmeUrl")
                        .HasColumnType("text")
                        .HasColumnName("readme_url");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text")
                        .HasColumnName("repo_url");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<float>("TotalHoursApproved")
                        .HasColumnType("real")
                        .HasColumnName("total_hours_approved");

                    b.Property<float>("TotalHoursRaw")
                        .HasColumnType("real")
                        .HasColumnName("total_hours_raw");

                    b.Property<float>("TrackedBuildHours")
                        .HasColumnType("real")
                        .HasColumnName("tracked_build_hours");

                    b.Property<float>("TrackedDesignHours")
                        .HasColumnType("real")
                        .HasColumnName("tracked_design_hours");

                    b.Property<int>("VoltsGranted")
                        .HasColumnType("integer")
                        .HasColumnName("volts_granted");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Torque.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<bool>("CompletedFirstTimeSetup")
                        .HasColumnType("boolean")
                        .HasColumnName("completed_first_time_setup");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HackatimeID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hackatime_id");

                    b.Property<string>("HackatimeToken")
                        .HasColumnType("text")
                        .HasColumnName("hackatime_token");

                    b.Property<string>("HcUserID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hc_user_id");

                    b.Property<string>("InternalNote")
                        .HasColumnType("text")
                        .HasColumnName("internal_note");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.PrimitiveCollection<Guid[]>("Projects")
                        .HasColumnType("uuid[]")
                        .HasColumnName("projects");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SlackUserID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slack_user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<bool>("VerificationStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("verification_status");

                    b.Property<int>("Volts")
                        .HasColumnType("integer")
                        .HasColumnName("volts");

                    b.Property<bool>("Watchlisted")
                        .HasColumnType("boolean")
                        .HasColumnName("watchlisted");

                    b.Property<bool>("YswsEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("ysws_eligible");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
